---
- name: install jack packages
  sudo: true
  yum: name='{{ item }}' state=present
  with_items:
    - fftw
    - jack-audio-connection-kit
    - jack-audio-connection-kit-example-clients
    - pulseaudio-module-jack
    - qjackctl
