---
- name: install clojure
  sudo: true
  yum: name=clojure state=present

- name: download lein 2
  get_url:
    url: 'https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein'
    dest: ~/bin
    mode: 0777

- name: enable the CCRMA repositories
  sudo: true
  yum:
    name: 'http://ccrma.stanford.edu/planetccrma/mirror/fedora/linux/planetccrma/20/i386/planetccrma-repo-1.1-3.fc20.ccrma.noarch.rpm'
    state: present

- name: install supercollider
  sudo: true
  yum: name=supercollider-world state=present