---
# tasks file for dotfiles
- name: install stow
  sudo: true
  yum: name=stow state=present

- name: clone dotfiles
  git:
    repo: '{{ dotfiles_repo }}'
    dest: ~/.dotfiles
    force: false
    update: false
  notify: link dotfiles