---
- name: bspwm | git clone
  git:
    repo: https://github.com/baskerville/bspwm.git
    dest: ~/code/open/bspwm
    force: false
    update: false

- name: bspwm | dependencies | install
  sudo: true
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - libxcb
    - xcb-util
    - xcb-util-devel
    - xcb-util-wm
    - xcb-util-wm-devel
    - xcb-util-keysyms
    - xcb-util-keysyms-devel

- name: bspwm | make
  command: make
  args:
    chdir: ~/code/open/bspwm
    creates: ~/code/open/bspwm/bspwm

- name: bspwm | make install
  sudo: true
  command: make install
  args:
    chdir: "/home/{{ ansible_user_id }}/code/open/bspwm"
    creates: /usr/local/bin/bspwm

- name: sxhkd | git clone
  git:
    repo: https://github.com/baskerville/sxhkd.git
    dest: ~/code/open/sxhkd
    force: false
    update: false

- name: sxhkd | make
  command: make
  args:
    chdir: ~/code/open/sxhkd
    creates: ~/code/open/sxhkd/sxhkd

- name: sxhkd | make install
  sudo: true
  command: make install
  args:
    chdir: "/home/{{ ansible_user_id }}/code/open/sxhkd"
    creates: /usr/local/bin/sxhkd