---
- name: clone cask
  git:
    repo: https://github.com/cask/cask.git
    dest: ~/.cask

- name: cask install
  command: ~/.cask/bin/cask install
  args:
    chdir: ~/.emacs.d
    creates: ~/.emacs.d/.cask