---
- name: enable rpmfusion
  sudo: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
    - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"

- name: add google-chrome repo
  sudo: true
  copy:
    src: google-chrome.repo
    dest: /etc/yum.repos.d/google-chrome.repo

- name: install packages
  sudo: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - adobe-source-code-pro-fonts
    - emacs
    - emacs-color-theme
    - gimp
    - gmrun
    - google-chrome-beta
    - inkscape
    - kmod-VirtualBox
    - lightdm
    - lightdm-gtk
    - rxvt-unicode-256color
    - tint2
    - VirtualBox
    - weechat