---
- name: nodejs | nvm | install
  git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.nvm

- name: nodejs | nvm | 0.10
  script: nvm-install.sh 0.10 --default

- name: nodejs | nvm | 0.11
  script: nvm-install.sh 0.11
