---
- name: nodejs | nvm | install
  git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.nvm

- name: nodejs | nvm | 0.10.29
  script: nvm-install.sh 0.10.29 --default

- name: nodejs | nvm | 0.11
  script: nvm-install.sh 0.11

- name: nodejs | global packages | install
  npm:
    name: "{{ item }}"
    executable: ~/.nvm/v0.10.29/bin/npm
    state: present
    global: true
  with_items:
    - bower
    - express
    - gulp
    - mocha
    - protractor

- name: nodejs | webdriver-manager | update
  command: ~/.nvm/v0.10.29/bin/webdriver-manager update
  args:
    creates: ~/.nvm/v0.10.29/lib/node_modules/protractor/selenium/selenium-server-standalone-2.42.2.jar