---
# tasks file for emacs
- name: install emacs
  sudo: true
  yum: name='{{ item }}' state=present
  with_items:
    - emacs
    - emacs-color-theme

- name: ensure systemd user unit dir exists
  file:
    dest: ~/.config/systemd/user
    state: directory

- name: create emacsd service
  copy:
    src: emacs.service
    dest: ~/.config/systemd/user/emacs.service

- name: enable emacsd
  shell: systemctl --user enable emacs && systemctl --user start emacs

- name: clone cask
  git:
    repo: https://github.com/cask/cask.git
    dest: ~/.cask
    force: false
    update: false

- name: cask install
  command: ~/.cask/bin/cask install
  args:
    chdir: ~/.emacs.d
    creates: ~/.emacs.d/.cask