---
- name: emacs | install
  sudo: true
  yum: pkg={{ item }} state=present
  with_items:
    - emacs
    - emacs-color-theme

- name: emacs | cask | install
  git:
    repo: https://github.com/cask/cask.git
    dest: ~/.cask

# ~/.emacs.d/Cask file must exist
- name: emacs | cask install
  command: ~/.cask/bin/cask install
  args:
    chdir: ~/.emacs.d
    creates: ~/.emacs.d/.cask
