---
- name: clone nvm
  git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.nvm
    version: v0.11.2

- name: install nodejs v0.10.29
  shell: source ~/.nvm/nvm.sh && nvm install v0.10.29 && nvm alias default v0.10.29
  args:
    creates: ~/.nvm/v0.10.29/bin/node

- name: install global npm packages
  npm:
    name: "{{ item }}"
    executable: ~/.nvm/v0.10.29/bin/npm
    state: present
    global: true
  with_items:
    - bower
    - broccoli-cli
    - grunt-cli
    - gulp
    - karma-cli
    - mocha
    - yo