---
# required package to use the selinux module
# NOTE: usually installed by default on fedora 20
- name: installing libselinux-python
  sudo: true
  yum:
    name: libselinux-python
    state: present

- name: disable selinux
  sudo: true
  selinux: state=disabled

- name: install packages
  sudo: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "@Development Tools"
    - "@C Development Tools and Libraries"
    - git
    - the_silver_searcher
    - tig
    - tmux
    - zsh