---
- name: install pip
  sudo: true
  easy_install: name=pip

- name: install virtualenv
  sudo: true
  pip: name=virtualenv

- name: install virtualenvwrapper
  sudo: true
  pip: name=virtualenvwrapper