---
# setup the home directory layout
- name: create home dirs
  file: name='~/{{ item }}' state=directory
  with_items:
    - bin
    - var
    - var/python_env

- name: install stow
  sudo: true
  yum: name=stow state=present

- name: clone dotfiles
  git:
    repo: '{{ essentials_dotfiles_repo }}'
    dest: ~/.dotfiles
    force: false
    update: false
  notify: link dotfiles