---
# setup some basic python packages for developing in python
- name: install python3
  sudo: true
  yum: name=python3 state=present

- name: install python3-setuptools
  sudo: true
  yum: name=python3-setuptools state=present

- name: install pip
  sudo: true
  easy_install: name=pip executable=easy_install-3.3

- name: install virtualenv
  sudo: true
  pip: name=virtualenv

- name: install virtualenvwrapper
  sudo: true
  pip: name=virtualenvwrapper